modify daemon to use $PYGDV_HOME VARIABLE

diff --git a/celery_ctl b/celery_ctl
--- a/celery_ctl
+++ b/celery_ctl
@@ -20,9 +20,13 @@
 
 #set -e
 
-PYGDV_HOME='/home/yo/git/pygdv'
-DEFAULT_PID_FILE=$PYGDV_HOME"/celeryd@%n.pid"
-DEFAULT_LOG_FILE=$PYGDV_HOME"/celeryd@%n.log"
+if [ -z $PYGDV_HOME ]; then
+    echo 'PYGDV_HOME variable is missing : please add ``export PYGDV_HOME="path/to/pyGDV/project"`` in your environment.'
+    exit 1
+fi
+
+DEFAULT_PID_FILE=$PYGDV_HOME"/daemon/celeryd@%n.pid"
+DEFAULT_LOG_FILE=$PYGDV_HOME"/log/celeryd@%n.log"
 DEFAULT_LOG_LEVEL="INFO"
 DEFAULT_NODES="celery"
 DEFAULT_CELERYD="-m celery.bin.celeryd_detach"
diff --git a/pygdv_clt b/pygdv_clt
--- a/pygdv_clt
+++ b/pygdv_clt
@@ -1,15 +1,20 @@
 #!/bin/sh -e
-PYGDV_HOME=/data/pygdv
+
+if [ -z $PYGDV_HOME ]; then
+    echo 'PYGDV_HOME variable is missing : please add ``export PYGDV_HOME="path/to/pyGDV/project"`` in your environment.'
+    exit 1
+fi
+
 
 case "$1" in
   start)
-    paster serve --daemon --pid-file=$PYGDV_HOME/paster.pid --log-file=$PYGDV_HOME/paster.log $PYGDV_HOME/production.ini start
+    paster serve --daemon --pid-file=$PYGDV_HOME/daemon/paster.pid --log-file=$PYGDV_HOME/log/paster.log $PYGDV_HOME/production.ini start
     ;;
   stop)
-    paster serve --daemon --pid-file=$PYGDV_HOME/paster.pid --log-file=$PYGDV_HOME/paster.log  $PYGDV_HOME/production.ini stop
+    paster serve --daemon --pid-file=$PYGDV_HOME/daemon/paster.pid --log-file=$PYGDV_HOME/log/paster.log  $PYGDV_HOME/production.ini stop
     ;;
   restart)
-    paster serve  --daemon --pid-file=$PYGDV_HOME/paster.pid --log-file=$PYGDV_HOME/paster.log $PYGDV_HOME/production.ini restart
+    paster serve  --daemon --pid-file=$PYGDV_HOME/daemon/paster.pid --log-file=$PYGDV_HOME/log/paster.log $PYGDV_HOME/production.ini restart
     ;;
   *)
     echo $"Usage: $0 {start|stop|restart}"
